//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.18 at 02:16:15 PM CET 
//


package org.bp.park;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.bp.park package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BookParkEntrance_QNAME = new QName("http://park.bp.org/", "bookParkEntrance");
    private final static QName _BookParkEntranceResponse_QNAME = new QName("http://park.bp.org/", "bookParkEntranceResponse");
    private final static QName _CancelBooking_QNAME = new QName("http://park.bp.org/", "cancelBooking");
    private final static QName _CancelBookingResponse_QNAME = new QName("http://park.bp.org/", "cancelBookingResponse");
    private final static QName _Fault_QNAME = new QName("http://park.bp.org/", "Fault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.bp.park
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BookParkEntrance }
     * 
     */
    public BookParkEntrance createBookParkEntrance() {
        return new BookParkEntrance();
    }

    /**
     * Create an instance of {@link BookParkEntranceResponse }
     * 
     */
    public BookParkEntranceResponse createBookParkEntranceResponse() {
        return new BookParkEntranceResponse();
    }

    /**
     * Create an instance of {@link CancelBooking }
     * 
     */
    public CancelBooking createCancelBooking() {
        return new CancelBooking();
    }

    /**
     * Create an instance of {@link CancelBookingResponse }
     * 
     */
    public CancelBookingResponse createCancelBookingResponse() {
        return new CancelBookingResponse();
    }

    /**
     * Create an instance of {@link Fault }
     * 
     */
    public Fault createFault() {
        return new Fault();
    }

    /**
     * Create an instance of {@link ParkEntranceTicket }
     * 
     */
    public ParkEntranceTicket createParkEntranceTicket() {
        return new ParkEntranceTicket();
    }

    /**
     * Create an instance of {@link EntranceFee }
     * 
     */
    public EntranceFee createEntranceFee() {
        return new EntranceFee();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link BookingInfo }
     * 
     */
    public BookingInfo createBookingInfo() {
        return new BookingInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BookParkEntrance }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BookParkEntrance }{@code >}
     */
    @XmlElementDecl(namespace = "http://park.bp.org/", name = "bookParkEntrance")
    public JAXBElement<BookParkEntrance> createBookParkEntrance(BookParkEntrance value) {
        return new JAXBElement<BookParkEntrance>(_BookParkEntrance_QNAME, BookParkEntrance.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BookParkEntranceResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BookParkEntranceResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://park.bp.org/", name = "bookParkEntranceResponse")
    public JAXBElement<BookParkEntranceResponse> createBookParkEntranceResponse(BookParkEntranceResponse value) {
        return new JAXBElement<BookParkEntranceResponse>(_BookParkEntranceResponse_QNAME, BookParkEntranceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelBooking }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CancelBooking }{@code >}
     */
    @XmlElementDecl(namespace = "http://park.bp.org/", name = "cancelBooking")
    public JAXBElement<CancelBooking> createCancelBooking(CancelBooking value) {
        return new JAXBElement<CancelBooking>(_CancelBooking_QNAME, CancelBooking.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelBookingResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CancelBookingResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://park.bp.org/", name = "cancelBookingResponse")
    public JAXBElement<CancelBookingResponse> createCancelBookingResponse(CancelBookingResponse value) {
        return new JAXBElement<CancelBookingResponse>(_CancelBookingResponse_QNAME, CancelBookingResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fault }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Fault }{@code >}
     */
    @XmlElementDecl(namespace = "http://park.bp.org/", name = "Fault")
    public JAXBElement<Fault> createFault(Fault value) {
        return new JAXBElement<Fault>(_Fault_QNAME, Fault.class, null, value);
    }

}
